# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'CustomMoment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FSCalendar'
  pod 'DropDown'
  pod 'NMapsMap'
  # Pods for CustomMoment

  target 'CustomMomentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomMomentUITests' do
    # Pods for testing
  end

end
