# Uncomment the next line to define a global platform for your project
platform :ios, '16.1'

#source 'https://github.com/CocoaPods/Specs.git'

target 'Moment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for Moment

  target 'MomentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MomentUITests' do
    # Pods for testing
  end

end
