# Generated by Django 3.2.13 on 2023-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='digit',
            field=models.CharField(max_length=14),
        ),
    ]
