# Generated by Django 3.2.13 on 2023-01-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('flavor', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locate', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_range', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CakeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeSideDeco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_deco', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_deco', to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeLettering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettering', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettering', to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=1024)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.cake')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.flavor')),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.location')),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.price')),
            ],
        ),
        migrations.CreateModel(
            name='CakeFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font', to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor', to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeDeco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deco', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deco', to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle', to='cakes.cake')),
            ],
        ),
    ]
