# Generated by Django 3.2.13 on 2023-03-14 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='cake_images/cake_default.png', null=True, upload_to='cake_images/')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_image', to='cakes.cake')),
            ],
        ),
    ]
