# Generated by Django 3.2.13 on 2023-04-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_alter_cakeimage_cake'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeInfoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_image', models.ImageField(blank=True, null=True, upload_to='cake_info_images/')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_image', to='cakes.cake')),
            ],
        ),
    ]
