# Generated by Django 3.2.13 on 2023-01-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deadline', models.IntegerField()),
                ('closed', models.BooleanField()),
                ('max_order', models.IntegerField()),
                ('store', models.ManyToManyField(to='stores.Store')),
            ],
        ),
    ]
