# Generated by Django 3.2.13 on 2023-01-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('calenders', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('pickup_time', models.TimeField(primary_key=True, serialize=False)),
                ('time_max_order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='stores.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='calender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='calenders.calender'),
        ),
        migrations.DeleteModel(
            name='CalenderStore',
        ),
        migrations.AddField(
            model_name='time',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='calenders.group'),
        ),
    ]
