# Generated by Django 3.2.13 on 2023-01-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0005_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='id',
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
