# Generated by Django 3.2.13 on 2023-01-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('calenders', '0006_auto_20230127_0637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('calender', 'store')},
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
