# Generated by Django 3.2.13 on 2023-01-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0010_auto_20230127_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='closed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='max_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
