# Generated by Django 3.2.13 on 2023-01-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0012_group_group_max_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='pickup_time',
            field=models.TimeField(),
        ),
    ]
