# Generated by Django 3.2.13 on 2023-01-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0013_auto_20230129_0047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='group',
            name='store',
        ),
    ]
