# Generated by Django 3.2.13 on 2023-02-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0017_group_group_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time_max_order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
