# Generated by Django 3.2.13 on 2023-03-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image1',
            field=models.ImageField(blank=True, default='media/store_images/store_image_default.png', null=True, upload_to='store_images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='image2',
            field=models.ImageField(blank=True, default='media/store_images/store_image_default.png', null=True, upload_to='store_images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='image3',
            field=models.ImageField(blank=True, default='media/store_images/store_image_default.png', null=True, upload_to='store_images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='image4',
            field=models.ImageField(blank=True, default='media/store_images/store_image_default.png', null=True, upload_to='store_images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='image5',
            field=models.ImageField(blank=True, default='media/store_images/store_image_default.png', null=True, upload_to='store_images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
