# Generated by Django 3.2.13 on 2023-04-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
