# Generated by Django 3.2.13 on 2023-01-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('flavor', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locate', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CakeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=1024)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.cake')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.flavor')),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.location')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.price')),
            ],
        ),
    ]
