# Generated by Django 3.2.13 on 2023-01-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_cakeinfo_flavor_location_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakeinfo',
            old_name='price',
            new_name='price_range',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='price_range',
        ),
    ]
