# Generated by Django 3.2.13 on 2023-01-26 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_alter_cakesize_cake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakesize',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='cake.cake'),
        ),
    ]
