# Generated by Django 3.2.13 on 2023-01-26 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('cake', '0006_alter_cakesize_cake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake', to='store.store'),
        ),
        migrations.AlterField(
            model_name='cakecandle',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle', to='cake.cake'),
        ),
        migrations.AlterField(
            model_name='cakecolor',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='cake.cake'),
        ),
        migrations.AlterField(
            model_name='cakedeco',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deco', to='cake.cake'),
        ),
        migrations.AlterField(
            model_name='cakedesign',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='cake.cake'),
        ),
        migrations.AlterField(
            model_name='cakeflavor',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor', to='cake.cake'),
        ),
        migrations.AlterField(
            model_name='cakefont',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font', to='cake.cake'),
        ),
        migrations.AlterField(
            model_name='cakelettering',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettering', to='cake.cake'),
        ),
        migrations.AlterField(
            model_name='cakepackage',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='cake.cake'),
        ),
        migrations.AlterField(
            model_name='cakepicture',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='cake.cake'),
        ),
        migrations.AlterField(
            model_name='cakesidedeco',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_deco', to='cake.cake'),
        ),
    ]
